### PR TITLE
Allowing CPU for predict

### PR DESCRIPTION
**Pull request by dmaluenda**
Using the CPU integration to predict (pick particles) is possible and viable (see benchmarks below) especially in streaming where the management of the GPU is crucial.

The drawback is: two conda environs are needed, double space and double installation time... maybe it can be not by default.

GPU: ~3s/mic
CPU: 5-6s/mic

I used batches of 4 and 10 for the benchmarks.

### CODE REVIEW

**Comment by azazellochg** [comment]
@dmaluenda you have to update README for this.

**Comment by dmaluenda** [comment]
I've also upgraded the version number from 3.0.1 to 3.0.2.

**Comment by dmaluenda** [comment]
Good point.

Let me do the following, to keep the environ name for the gpu version, while adding a new one for the cpu version.

Maybe it's better in this way.

**Comment by dmaluenda** [comment]
Ok, now all regarding the GPU implementation reads like before, but the CPU implementation is added. This should prevent any issue for that people who already installed cryolo.

In addition, the CPU implementation is not installed by default and a validation is added to the predict protocol in order to warn users if not installed and try to use it.

**Comment by dmaluenda** [comment]
Sorry, I updated the Changes.txt not the readme..

I will do it

**Comment by dmaluenda** [comment]
Done!

**Pull request merged**
