### PR TITLE
Python3 migration jj review emlib

### PR DESCRIPTION
**Pull request by JorMaister**

### CODE REVIEW

**Comment by delarosatrevin** [comment]
All tests passed here in this branch...but this PR was against master. Was that the intention? It might break Scipion2 installations using the repository code. I think it should be reverted and these changes merged into python3_migration one.

**Comment by JorMaister** [comment]
My fault, I didn't notice it was against master.

**Comment by delarosatrevin** [comment]
No problem @JorMaister fault here is shared with the reviewer (who actually merged it) ;)
Anyway, master should be restored to the previous state.

**Comment by JorMaister** [comment]
I have reverted to the last commint origin/master and created a new PR, the same as this one, but to python3_migration.

**Pull request merged**
