### PR TITLE
add new version

### PR DESCRIPTION
**Pull request by azazellochg**
Tests are passing

### CODE REVIEW

**Review by fonsecareyna82 — COMMENTED** [review]
If I already have cryolo installed, which generated an environment, now when installing the new version, another env is created. Could we delete the previous one in the command itself so as not to have an unused env?

**Comment by fonsecareyna82** [comment]
It's not a problem for me. In the case of CS, when I generate a new env for pyem, I delete the previous one in the installation command itself.

**Comment by azazellochg** [comment]
Or imagine that the new cryolo doesnt work on existing gpu/hardware and you want to revert. Now you have lost the old env and instead of simply changing the config file you need to install it again.

**Comment by delarosatrevin** [comment]
I agree with Grigory, we should be extra careful and not delete things. It is better to play safe and let the user(or sysadmin) do some cleaning work. The example that Grigory mention has happened to me, that I need to go back to a previous working version, so better not to delete.

**Pull request merged**
