### PR TITLE
Streaming fixes in picking protocol

### LINKED ISSUE #46: Different results 1 GPU vs 4 GPUs
I found a very strange behavior when using cryolo picking. 

pyworkflow: 3.0.5
plugin: sphire v: 3.0.4

I was running relion ' motioncor2 and the stream output used as input for cryolo picking.

The first issue was that running with 5 threads and 4 GPUs (0 1 2 3) and 4 cores per process, I had many micrographs with 0 coordiantes. So, for an input of approx 170 mics, there was only 3k output coordinates. (batch size of 16 mics)

Then, if I run the same jobs, with the same parameters, except only 1 threads and GPU 0, all micrographs get picked and the output set of coordinates for the same number of input mics was about 7k coordinates! 

@pconesa @azazellochg This is really bad for using multi-GPU machines (either local or cluster) to pick and I'm worried if this is only cryolo or the base picking class with threads and streaming and batches.

### PR DESCRIPTION
**Pull request by JorMaister**
Fixes #46

### CODE REVIEW

**Review by azazellochg — APPROVED** [review]
Great! It seems to work!

**Review by pconesa — CHANGES_REQUESTED** [review]
Could  you bump the version, so we can release the fix?

**Comment by delarosatrevin** [comment]
I think there is still some race conditions here...even if the folders are not deleted, the files are being moved. Does not affect this parsing coordinates for batch? I haven't really check, just looking at the code.

**Comment by pconesa** [comment]
We have tested this and seems to be working with 3 threads, 2 GPUs.
Are we missing anything?

**Pull request merged**
